-- delete from contaprs
-- select * from categorias
-- delete from categorias
--dbcc checkident('categorias',RESEED,0);
--SET IDENTITY_INSERT dbo.Categorias ON;  


insert categorias (categoriaid,nome,tipo) values(1,'Encargos Funcionários - Alimentação','P')
insert categorias (categoriaid,nome,tipo) values(2,'Folha de Pagamento','P')
insert categorias (categoriaid,nome,tipo) values(3,'Aluguel/IPTU','P')
insert categorias (categoriaid,nome,tipo) values(4,'Condomínio','P')
insert categorias (categoriaid,nome,tipo) values(5,'Energia','P')
insert categorias (categoriaid,nome,tipo) values(6,'Telefonia Fixa','P')
insert categorias (categoriaid,nome,tipo) values(7,'Telefonia Móvel','P')
insert categorias (categoriaid,nome,tipo) values(8,'Internet','P')
insert categorias (categoriaid,nome,tipo) values(9,'Cafeteria','P')
insert categorias (categoriaid,nome,tipo) values(10,'Material de Escritório','P')
insert categorias (categoriaid,nome,tipo) values(11,'Higiene','P')
insert categorias (categoriaid,nome,tipo) values(12,'Estacionamento','P')
insert categorias (categoriaid,nome,tipo) values(13,'Comissão','P')
insert categorias (categoriaid,nome,tipo) values(14,'Reembolso','P')
insert categorias (categoriaid,nome,tipo) values(15,'Impostos - Retenção 4,65% (Cód. 5952)','P')
insert categorias (categoriaid,nome,tipo) values(16,'Prestação de Serviços/Terceiros','P')
insert categorias (categoriaid,nome,tipo) values(17,'Seguro de Vida','P')
insert categorias (categoriaid,nome,tipo) values(18,'Seguro Incêndio','P')
insert categorias (categoriaid,nome,tipo) values(19,'Impostos - IR Serviços ( Cód. 1708)','P')
insert categorias (categoriaid,nome,tipo) values(20,'Locação','R')
insert categorias (categoriaid,nome,tipo) values(24,'Encargos Funcionários - Assist. Médica e Odontológica','P')
insert categorias (categoriaid,nome,tipo) values(25,'Remuneração Funcionário','P')
insert categorias (categoriaid,nome,tipo) values(26,'Serviços','R')
insert categorias (categoriaid,nome,tipo) values(27,'Licença ou Aluguel de Softwares','P')
insert categorias (categoriaid,nome,tipo) values(28,'Equipamentos','P')
insert categorias (categoriaid,nome,tipo) values(29,'FGTS','P')
insert categorias (categoriaid,nome,tipo) values(30,'Contribuição Assistencial','P')
insert categorias (categoriaid,nome,tipo) values(31,'Impostos - IRF Assalariado (Cod. 0561)','P')
insert categorias (categoriaid,nome,tipo) values(32,'Impostos - Contr. Previd.Sobre Receita Bruta - Art. 8º Lei 12.546/2011 (Cod. 2991)','P')
insert categorias (categoriaid,nome,tipo) values(33,'GPS','P')
insert categorias (categoriaid,nome,tipo) values(34,'Impostos - ISS - Imposto Sobre Serviços de Qualquer Natureza','P')
insert categorias (categoriaid,nome,tipo) values(35,'Impostos -  IRPJ - Lucro Presumido (cod. 2089)','P')
insert categorias (categoriaid,nome,tipo) values(36,'Impostos - CSLL - Contribuição Social sobre o Lucro Líquido  (cod. 2372)','P')
insert categorias (categoriaid,nome,tipo) values(37,'Impostos - PIS sobre Faturamento (cod. 8109) ','P')
insert categorias (categoriaid,nome,tipo) values(38,'Impostos - COFINS (cod. 2172)','P')
insert categorias (categoriaid,nome,tipo) values(39,'Viagens','P')
insert categorias (categoriaid,nome,tipo) values(40,'Transporte','P')
insert categorias (categoriaid,nome,tipo) values(41,'PLR Sócios','P')
insert categorias (categoriaid,nome,tipo) values(42,'PLR','P')
insert categorias (categoriaid,nome,tipo) values(43,'Advogados','P')
insert categorias (categoriaid,nome,tipo) values(44,'Despesas Internas','P')
insert categorias (categoriaid,nome,tipo) values(45,'Venda','R')
insert categorias (categoriaid,nome,tipo) values(46,'Internet Móvel','P')
insert categorias (categoriaid,nome,tipo) values(47,'Tarifas Bancárias','P')
insert categorias (categoriaid,nome,tipo) values(48,'Encargos Funcionários - Vale Transporte','P')
insert categorias (categoriaid,nome,tipo) values(51,'Férias','P')
insert categorias (categoriaid,nome,tipo) values(52,'Manutenção','R')
insert categorias (categoriaid,nome,tipo) values(53,'Cartão de Crédito','P')
insert categorias (categoriaid,nome,tipo) values(54,'Brindes','P')
insert categorias (categoriaid,nome,tipo) values(55,'Marketing','P')
insert categorias (categoriaid,nome,tipo) values(56,'ICMS (Imposto sobre Circulação de Mercadorias e Serviços)','P')
insert categorias (categoriaid,nome,tipo) values(57,'Verbas Rescisórias','P')
insert categorias (categoriaid,nome,tipo) values(58,'Contribuição Sindical','P')
insert categorias (categoriaid,nome,tipo) values(59,'Impostos - IRF - Aluguéis e Royalties pagos à Pessoa Física (Cod. 3208)','P')
insert categorias (categoriaid,nome,tipo) values(60,'13º Salário','P')
insert categorias (categoriaid,nome,tipo) values(61,'Capitalização','P')
insert categorias (categoriaid,nome,tipo) values(62,'Aluguel de Carro','P')
insert categorias (categoriaid,nome,tipo) values(63,'Empréstimo','P')
insert categorias (categoriaid,nome,tipo) values(64,'Impostos - Multas Previstas na Legislação do Seguro Desemprego e Abono Salarial (cod. 2877)','P')
insert categorias (categoriaid,nome,tipo) values(65,'Patrocínio','P')
insert categorias (categoriaid,nome,tipo) values(66,'Estorno ','R')
insert categorias (categoriaid,nome,tipo) values(67,'Móveis','P')
insert categorias (categoriaid,nome,tipo) values(68,'Evento','P')
insert categorias (categoriaid,nome,tipo) values(69,'Rescisão de Sócios','P')
insert categorias (categoriaid,nome,tipo) values(70,'Despesa Administrativa','P')
insert categorias (categoriaid,nome,tipo) values(71,'Estorno Cliente','P')
insert categorias (categoriaid,nome,tipo) values(72,'Imposto - Contribuição Retida sobre a NF/Fatura da Empresa Prestadora de Serviço (cod. 2631)','P')
insert categorias (categoriaid,nome,tipo) values(73,'Impostos - ICMS Consumidor Final Não Contribuinte Outra UF por Operação (Cod.100102)','P')
