Select * from situacaos
delete from situacaos
dbcc checkident('situacaos',reseed,0)
insert situacaos (nome,cor) values ('Em análise','white')
insert situacaos (nome,cor) values ('Aceita','yellow')
insert situacaos (nome,cor) values ('Negada','red')
insert situacaos (nome,cor) values ('Liberada','blue')
insert situacaos (nome,cor) values ('Faturando','green')
insert situacaos (nome,cor) values ('Cancelada','white')
insert situacaos (nome,cor) values ('Aguardando PO','orange')

Select * from  SituacaoProjetos

insert SituacaoProjetos (nome,cor) values ('Em execução','green')
insert SituacaoProjetos (nome,cor) values ('Stand by','red')
insert SituacaoProjetos (nome,cor) values ('Fechado','blue')

Select * from situacaorenovacaos
insert situacaorenovacaos (nome,cor) values ('Ativo','Green')
insert situacaorenovacaos (nome,cor) values ('Concluido','Blue')

Select * from meses
insert meses (mes,nome) values (1,'Janeiro')
insert meses (mes,nome) values (2,'Fevereiro')
insert meses (mes,nome) values (3,'Março')
insert meses (mes,nome) values (4,'Abril')
insert meses (mes,nome) values (5,'Maio')
insert meses (mes,nome) values (6,'Junho')
insert meses (mes,nome) values (7,'Julho')
insert meses (mes,nome) values (8,'Agosto')
insert meses (mes,nome) values (9,'Setembro')
insert meses (mes,nome) values (10,'Outubro')
insert meses (mes,nome) values (11,'Novembro')
insert meses (mes,nome) values (12,'Dezembro')

Select * from  permissaos
Select * from aspnetroles

insert permissaos (roleid,pro_view,pro_edit,rec_edit,rec_view,pag_edit,pag_view,cad_edit,cad_view,rep_edit,rep_view,ree_edit,ree_view,prj_edit,prj_view,ctt_edit,ctt_view,rem_edit,rem_view)
values ('025f4e01-7921-48c2-8f93-59e1aca44f7b',1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1)


Select * from categorias
insert categorias (nome,tipo) values ('Encargos Funcionários - Alimentação','P')
insert categorias (nome,tipo) values ('Folha de Pagamento','P')
insert categorias (nome,tipo) values ('Aluguel/IPTU','P')
insert categorias (nome,tipo) values ('Condomínio','P')
insert categorias (nome,tipo) values ('Energia	','P')
insert categorias (nome,tipo) values ('Telefonia Fixa','P')
insert categorias (nome,tipo) values ('Telefonia Móvel','P')
insert categorias (nome,tipo) values ('Internet','P')
insert categorias (nome,tipo) values ('Cafeteria','P')
insert categorias (nome,tipo) values ('Material de Escritório','P')
insert categorias (nome,tipo) values ('Higiene','P')
insert categorias (nome,tipo) values ('Estacionamento','P')
insert categorias (nome,tipo) values ('Comissão','P')
insert categorias (nome,tipo) values ('Reembolso','P')
insert categorias (nome,tipo) values ('Impostos - Retenção 4,65% (Cód. 5952)','P')
insert categorias (nome,tipo) values ('Prestação de Serviços/Terceiros','P')
insert categorias (nome,tipo) values ('Seguro de Vida','P')
insert categorias (nome,tipo) values ('Seguro Incêndio','P')
insert categorias (nome,tipo) values ('Impostos - IR Serviços ( Cód. 1708)','P')
insert categorias (nome,tipo) values ('Locação','R')
insert categorias (nome,tipo) values ('Encargos Funcionários - Assist. Médica e Odontológica','P')
insert categorias (nome,tipo) values ('Remuneração Funcionário','P')
insert categorias (nome,tipo) values ('Serviços','R')
insert categorias (nome,tipo) values ('Licença ou Aluguel de Softwares','P')
insert categorias (nome,tipo) values ('Equipamentos','P')
insert categorias (nome,tipo) values ('FGTS','P')
insert categorias (nome,tipo) values ('Contribuição Assistencial','P')
insert categorias (nome,tipo) values ('Impostos - IRF Assalariado (Cod. 0561)','P')
insert categorias (nome,tipo) values ('Impostos - Contr. Previd.Sobre Receita Bruta - Art. 8º Lei 12.546/2011 (Cod. 2991)','P')
insert categorias (nome,tipo) values ('GPS','P')
insert categorias (nome,tipo) values ('Impostos - ISS - Imposto Sobre Serviços de Qualquer Natureza','P')
insert categorias (nome,tipo) values ('Impostos -  IRPJ - Lucro Presumido (cod. 2089)','P')
insert categorias (nome,tipo) values ('Impostos - CSLL - Contribuição Social sobre o Lucro Líquido  (cod. 2372)','P')
insert categorias (nome,tipo) values ('Impostos - PIS sobre Faturamento (cod. 8109)','P')
insert categorias (nome,tipo) values ('Impostos - COFINS (cod. 2172)','P')
insert categorias (nome,tipo) values ('Viagens','P')
insert categorias (nome,tipo) values ('Transporte','P')
insert categorias (nome,tipo) values ('PLR Sócios','P')
insert categorias (nome,tipo) values ('PLR','P')
insert categorias (nome,tipo) values ('Advogados','P')
insert categorias (nome,tipo) values ('Despesas Internas','P')
insert categorias (nome,tipo) values ('Venda','R')
insert categorias (nome,tipo) values ('Internet Móvel','P')
insert categorias (nome,tipo) values ('Tarifas Bancárias','P')
insert categorias (nome,tipo) values ('Encargos Funcionários - Vale Transporte','P')
insert categorias (nome,tipo) values ('Férias','P')
insert categorias (nome,tipo) values ('Manutenção','R')
insert categorias (nome,tipo) values ('Cartão de Crédito','P')
insert categorias (nome,tipo) values ('Brindes','P')
insert categorias (nome,tipo) values ('Marketing','P')
insert categorias (nome,tipo) values ('ICMS (Imposto sobre Circulação de Mercadorias e Serviços)','P')
insert categorias (nome,tipo) values ('Verbas Rescisórias','P')
5insert categorias (nome,tipo) values ('Contribuição Sindical','P')
insert categorias (nome,tipo) values ('IRF - Aluguéis e Royalties pagos à Pessoa Física (Cod. 3208)','P')
insert categorias (nome,tipo) values ('13º Salário','P')
